### ISSUE TITLE
Duplication of schemas, addition of "-key" or "-value" to subjects

### ISSUE THREAD

**Issue by m0baxter** [marcosschroh/python-schema-registry-client#40] opened 2020-02-13 20:12 UTC
Regardless of whether a schema is already in the registry a new one with `"-key"` or `"-value"` is created by serializers.

I was able to fix this by changing this line

https://github.com/marcosschroh/python-schema-registry-client/blob/a0528cb85474e428ca3c68cb8491c3c1c8f68846/schema_registry/serializers/message_serializer.py#L79

I am not sure it this is the intended behaviour, it took me a while to figure out why my schema's were being duplicated, I could see how this might be a problem if you interact with many schemas.

**Comment by marcosschroh** [comment] 2020-02-13 22:41
Hi @m0baxter 

It was intended. According to the `schema registry` [documentation](https://docs.confluent.io/3.2.2/schema-registry/docs/api.html#post--subjects-(string-%20subject)-versions) you can register the same schema multiple times under the same subject or not and the `schema_id` will be always the same. So, I think it should not be a problem. Can you see multiple schemas created inside the schema registry server?

Which changes did you made?

**Comment by m0baxter** [comment] 2020-02-13 22:48
I just changed it to
```
subject = f"{subject}"
```
to stop it from creating more subjects. I could have just as easily commented it out I think.

The problem is that it was creating multiple subjects. For example I registered "testing" and it would register a second subject "testing-values".

I think this is happening due to the fact that `schema_name_to_id` is initially an empty `dict` it doesn't look for existing subjects on the server.

**Comment by marcosschroh** [comment] 2020-02-14 00:05
Oh, I understand now.

So, a flow could be:

1. You register a schema under a specific subject (let's say `my-subject`) using an instance of `SchemaRegistryClient` (or the schema was already present)
2. With the same schema you call the `message_serializer`, and the `mesage_serializer` use `my-subject-value` or `my-subject-key` according to the `is_key` keyword, and registers the same schema under the new subject.

In theory, the `schema_id` returned should be the same in both cases, however, the version of the schema may be different. 

So, I think would be a good idea to remove the keyword `is_key` and use `subject` directly. I think the cache should not be a problem because the subject and the schema will be the same on both cases.

What do you think?

**Comment by m0baxter** [comment] 2020-02-14 14:04
Sorry if I wasn't being clear about the use case, your description matches what I am attempting to do so we are on the same page now at least.

your solution sounds correct to me.

Also reading the documentation you linked to seems to imply that it `my-subject`, `my-subject-key`, and `my-subject-value` would all point to the same schema (have the same end point in `/schemas/ids/<Ischema_id>`) so it may not actually matter. Ultimately it may be purely a function of aesthetics, keeping `/subjects` in the registry less cluttered.

**Comment by marcosschroh** [comment] 2020-02-14 15:48
cool! Do you want to send a `PR`?

**Comment by marcosschroh** [comment] 2020-02-19 18:30
closed by https://github.com/marcosschroh/python-schema-registry-client/pull/41

**Closed by marcosschroh** 2020-02-19 18:30 UTC
